### ISSUE TITLE
 ./Example/DetectConfig.py -d ./test/n0_flow.txt --method='mfmb' --pic_show fails

### ISSUE THREAD

**Issue by hbhzwj** [hbhzwj/SADIT#6]
jayram@ubuntu:~/sadit$ ./cmdsadit detect -c ./Example/DetectConfig.py -d ./test/n0_flow.txt --method='mfmb' --pic_show
[warning] socketIO_client is not found. Real-time ability is disabled
--> Use [matplotlib] as plot backend
--> [warning] cannot import sql related function, reading for sql server is not supported
WARNING:util:Cannot find [socketIO_client], real-time ability is disabled.
WARNING:util:Cannot import sql related function, reading for sql server is not supported
Probabably you forgot to specify some options? run cmdsadit <exper> -h for more information.
Traceback (most recent call last):
  File "./cmdsadit", line 74, in main
    get_exper(args.experiment, res_args).run()
  File "/home/jayram/sadit/Detector/gad/Experiment/Detect.py", line 93, in run
    detector = self.detect()
  File "/home/jayram/sadit/Detector/gad/Experiment/Detect.py", line 89, in detect
    self.res_args)
  File "/home/jayram/sadit/Detector/gad/Detector/API.py", line 97, in detect
    detector.detect(data_handler)
  File "/home/jayram/sadit/Detector/gad/Detector/StoDetector.py", line 439, in detect
    self._init_for_threshold_rule()
  File "/home/jayram/sadit/Detector/gad/Detector/StoDetector.py", line 349, in _init_for_threshold_rule
    pmf, Pmb = self.norm_em
TypeError: 'NoneType' object is not iterable

**Comment by jingzbu** [comment]
If checking out to the ```ThresExper``` branch, and change the command to:
```./cmdsadit Detect -c ./Example/DetectConfig.py -d ./test/n0_flow.txt --method='mfmb' --pic_show```
then there the issue would not exist. 

In the ```master``` branch, the new Hoeffding rule has not been fully implemented... For a temporal experimental use, we suggest checking out to the ```ThresExper``` branch right after cloning the SADIT package. We will work on merging these two branches later.

**Comment by hbhzwj** [comment]
The NewHoeffdingRule branch used cython to compile modules (though cython dependency will be removed after NewHoeffdingRule is merged to master). 

If there is the error of

    'numpy/arrayobject.h' file not found

Please refer to https://github.com/hbhzwj/GAD/wiki#got-error-message-fatal-error-numpyarrayobjecth-file-not-found for solution

**Comment by jingzbu** [comment]
Now it works.
